services:
  mongodb:
    image: zcube/bitnami-compat-mongodb:6.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=password
      - MONGODB_DATABASE=deposits
    networks:
      - default

  # app:
  #   build: .
  #   container_name: app
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     - mongodb
  #   environment:
  #     - MONGO_URI=mongodb://user:password@mongodb:27017/deposits
  #     - PORT=4000
  #     - NODE_ENV=production
  #   volumes:
  #     - ./logs:/app/logs
  #   env_file:
  #     - .env
  #   networks:
  #     - default

  # prometheus:
  #   build:
  #     context: ./grafana
  #     dockerfile: Dockerfile.prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - prometheus_data:/prometheus
  #   depends_on:
  #     - app
  #   networks:
  #     - default

  # grafana:
  #   build:
  #     context: ./grafana
  #     dockerfile: Dockerfile.grafana
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - grafana_data:/var/lib/grafana
  #   depends_on:
  #     - prometheus
  #   networks:
  #     - default

networks:
  default:

volumes:
  mongodb_data:
  prometheus_data:
  grafana_data:
