services:
  mongodb:
    image: zcube/bitnami-compat-mongodb:6.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=password
      - MONGODB_DATABASE=deposits
    networks:
      - default

networks:
  default:

volumes:
  mongodb_data:
