global:
  scrape_interval: 10s 
  evaluation_interval: 10s

scrape_configs:
  - job_name: "deposits_metrics"
    metrics_path: "/metrics" 
    scheme: "http"
    static_configs:
      - targets: ["app:4000"]
    scrape_interval: 10s
